using System.Collections.Generic;

namespace Common.DataModels
{
    public enum canditateOrboundary
    {
        Canditate,
        Boundary
    }

    public static class Globals
    {
        public static List<OldWord> top50words = new List<OldWord>() {
              new OldWord() { word = "the" },
              new OldWord() { word = "of"},
              new OldWord() { word = "and" },
              new OldWord() { word = "a"},
              new OldWord() { word = "in" },
              new OldWord() { word = "to" },
              new OldWord() { word = "it"},
              new OldWord() { word = "is" },
              new OldWord() { word = "was"},
              new OldWord() { word = "i" },
              new OldWord() { word = "for"},
              new OldWord() { word = "that" },
              new OldWord() { word = "you"},
              new OldWord() { word = "he" },
              new OldWord() { word = "be"},
              new OldWord() { word = "with" },
              new OldWord() { word = "on"},
              new OldWord() { word = "by" },
              new OldWord() { word = "at"},
              new OldWord() { word = "have" },
              new OldWord() { word = "are"},
              new OldWord() { word = "not" },
              new OldWord() { word = "this"},
              new OldWord() { word = "but"},
              new OldWord() { word = "had" },
              new OldWord() { word = "they"},
              new OldWord() { word = "his" },
              new OldWord() { word = "from"},
              new OldWord() { word = "she" },
              new OldWord() { word = "which"},
              new OldWord() { word = "or" },
              new OldWord() { word = "we"},
              new OldWord() { word = "an" },
              new OldWord() { word = "were"},
              new OldWord() { word = "as" },
              new OldWord() { word = "do"},
              new OldWord() { word = "been" },
              new OldWord() { word = "their"},
              new OldWord() { word = "has"},
              new OldWord() { word = "would" },
              new OldWord() { word = "there"},
              new OldWord() { word = "what" },
              new OldWord() { word = "will"},
              new OldWord() { word = "all" },
              new OldWord() { word = "if"},
              new OldWord() { word = "can" },
              new OldWord() { word = "her"},
              new OldWord() { word = "said" },
              new OldWord() { word = "who"}
        };

        public static List<string> top50strings = new List<string>() {
            "the" ,
            "of",
            "and" ,
            "a",
            "in" ,
            "to" ,
            "it",
            "is" ,
            "was",
            "i" ,
            "for",
            "that" ,
            "you",
            "he" ,
            "be",
            "with" ,
            "on",
            "by" ,
            "at",
            "have" ,
            "are",
            "not" ,
            "this",
            "but",
            "had" ,
            "they",
            "his" ,
            "from",
            "she" ,
            "which",
            "or" ,
            "we",
            "an" ,
            "were",
            "as" ,
            "do",
            "been" ,
            "their",
            "has",
            "would" ,
            "there",
            "what" ,
            "will",
            "all" ,
            "if",
            "can" ,
            "her",
            "said" ,
            "who"
        };
    }
}